### ISSUE TITLE
Test framework in purely Gaussian case

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/jax-lensing#12]
This issue is to track the tests we want to run on a purely Gaussian case, for instance to compare to the Wiener filter solution. 

@NiallJeffrey I'm tagging you on this as I know you have been looking at something like this.

What tests do you think we should include, and do  you already have some notebooks for this?

**Comment by NiallJeffrey** [comment]
Yeah - I currently have the Gaussian sampler working (not with Jax in the end) but it is currently with a noisy convergence input (not a noisy shear input)

**Comment by EiffL** [comment]
@NiallJeffrey As we are making progress on the paper, would you have time to think about this point? No worries if not, we can either descope or we can try to set it up on our own.

**Comment by EiffL** [comment]
Things we want to try to do:

- [ ] Validate Gaussian log prior
- [ ] Compute MAP in Gaussian case 
- [ ] Sample maps in Gaussian case

Once this is done, the type of results we want to check the power spectrum of theory vs training map vs Gaussian sample vs MAP/Mean.

**Comment by b-remy** [comment]
Developments in: https://github.com/CosmoStat/jax-lensing/blob/training-script/notebooks/Gaussian_prior.ipynb
To compute the gaussian prior we need to compute a Fourier map from a power spectrum and then do the ratio with the one computed from a convergence map.
In order to validate this computations, I compared the ratio of the 1d power spectrum we have access to, and the 2d power spectrum we aim to compute.
<img width="841" alt="image" src="https://user-images.githubusercontent.com/30293694/109043240-67ffec80-76d1-11eb-80fe-d39d7261ca4c.png">
mean ratio is `0.75`
<img width="656" alt="image" src="https://user-images.githubusercontent.com/30293694/109043016-28d19b80-76d1-11eb-862c-22f2543cb124.png">
mean ratio is `0.70`

**Comment by b-remy** [comment]
Quick result comparing the MAP and the Posterior Mean over 400 samples with a Gaussian prior:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/30293694/109219294-b5568980-77b7-11eb-9af8-bcbec7d1a0e8.png">

code : https://github.com/CosmoStat/jax-lensing/blob/map-script/notebooks/Gaussian_prior2.ipynb

**Comment by NiallJeffrey** [comment]
I've added the Wiener filter and sampler with a notebook here: 
https://github.com/CosmoStat/jax-lensing/blob/gaussian_prior/notebooks/wiener_sampler.ipynb
You can compare the results from https://github.com/CosmoStat/jax-lensing/blob/map-script/notebooks/Gaussian_prior2.ipynb
Unfortunately there's a weird problem with the sampler that I can't explain - so the samples have a peak at the origin - @EiffL  any ideas?

**Comment by EiffL** [comment]
That's really cool! Thanks Niall! Really not obvious why you have this dot at the center ^^'

**Comment by NiallJeffrey** [comment]
I've now fixed the dot. It was a complex conjugate thing about have the E and B field samples being real, that weirdly led to a single bright pixel.  In https://github.com/CosmoStat/jax-lensing/blob/gaussian_prior/notebooks/wiener_sampler.ipynb there is now the Wiener posterior sampler on the COSMOS data
