### ISSUE TITLE
Prepare full COSMOS shape catalog

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/jax-lensing#7]
So far we have used the bright sample from the shape catalog of [Schrabback et al.](https://arxiv.org/abs/0911.0053), which already has a very good number density, but we probably want to switch to the full sample, including fainter sources, which goes to higher redshifts.

The thing to do here is to write a notebook doing the following:
  - [x] : Loading lensing data
  - [x] : Applying any necessary quality cuts
  - [x] : Bin ellipticity catalog on map with given pixel size [TBD, depends on simulations]
  - [x] : Create map of number of galaxies per pixels as fits file
  - [x] : Create binary mask for empty pixels as fits file
  - [x] : Create binned ellipticity  maps as fits file

**Comment by b-remy** [comment]
We now have the fits files described above. They were made from the full catalog of Schrabback et al., without galaxies from the bright catalog with redshift measurement problem that were discarded.

Also it turns out that the bright and the faint catalogs have not the same missing data regions. Sometime faint galaxies overlap missing data region of the bright catalog. If this is an issue, we could combine masks in the final binary mask, but we would loose information...
