### ISSUE TITLE
Prepare COSMOS redshift distribution

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/jax-lensing#9]
Once we have built our shape catalog (done in #9 ), we can produce the corresponding n(z) that will be required for generating the simulation data.

The deliverable here should be a small fits file storing the n(z) for our defined lensing sample.

**Comment by liuxx479** [comment]
Hi @b-remy @EiffL , since P(z) drops already quite a lot at z=2.6, I don't imagine there is a significant loss of signal due to the removal of z>2.6 galaxies? Why don't we apply a z_cut and use only galaxies at z<2.6?  In addition, this is already significantly higher than the z_cut applied by all existing large lensing surveys (most z_cut<1.3-1.5).

**Comment by EiffL** [comment]
Hi @liuxx479 :-) Well the problem is that we can't easily apply a cut at z=2.6 in the data, for the faint galaxies we don't have individual galaxy redshifts but only an overall redshift distribution for the entire sample. 
The COSMOS survey is a lot better than common current surveys.

**Comment by liuxx479** [comment]
Ok I see. Ok maybe we can just recycle z=2.6 plane as @EiffL suggested. If @b-remy send me the COSMOS Pz I can play around and check if the lensing kernel is somewhat reasonable with this assumption.

**Comment by liuxx479** [comment]
Thanks @b-remy for sending me the COSMOS pz. Could you please send me the full P(z) (all the way to z=5) so I can check if it is safe to recycle the z=2.6 map? 

I was able to run a quick test, by simply extrapolating the current pz to z=5. 

![image](https://user-images.githubusercontent.com/2658222/99465120-7c706400-28ee-11eb-943a-7b1fa5bbc377.png)

blue dash: COSMOS pz (with linear extrapolation beyond z=2.6)
orange: modified pz, where I assume all the z>2.6 galaxies are at z-2.6 (i.e. recycling kappaTNG z=2.6 map)
green dash: lensing kernel for original pz
red solid: lensing kernel for modified pz

The difference seem very small, so I'd say we're safe to just recycle the z=2.6 map.

**Comment by b-remy** [comment]
Hi @liuxx479, I looked closer to the different catalogs and documentation and noticed that the redshift catalog for the faint galaxies had a factor x100. This is why the addition of the bright catalog didn't have much influence of the final redshift distribution...

So I built the full catalog redshift distribution more carefully and checked with the plots of [Schrabback et al](https://arxiv.org/abs/0911.0053).

Considering the cleaned bright catalog (without problematic redshift measurement z_photo < 0.6) and the relevant normalisation of the faint redshift distrib, I were able to reproduce the Figure 6 of [Schrabback et al](https://arxiv.org/abs/0911.0053). Now I have more confidence for the final redshift distribution.

![image](https://user-images.githubusercontent.com/30293694/99719143-35c86880-2aac-11eb-821b-5325967eb8c4.png)

I sent you the data to reproduce the histogram of the full catalog (in black above), but also a file containing all the redshifts of the full catalog in case you need to build a finer histogram or need it to do interpolation.

Hopping that it helps you to build the lensing kernel and check the recycling :)

**Comment by liuxx479** [comment]
Using @b-remy 's new COSMOS Pz, I modified the Pz such that all z>2.6 galaxies fall in the last bin (z~=2.6) with a weight A. Here is a few modification, and I plan to use the curve with A=2.5 since it matches the peak of lensing kernel W(z) best. Let me know if this sounds good to you and I will start process the maps.

![download](https://user-images.githubusercontent.com/2658222/100918652-9fbe1600-348d-11eb-9e20-e3fc41e5c5fc.png)

Notebook used to generate above plot: [https://github.com/liuxx479/pzCOSMOS/blob/main/prep_kappaTNG.ipynb](https://github.com/liuxx479/pzCOSMOS/blob/main/prep_kappaTNG.ipynb)

**Comment by liuxx479** [comment]
@EiffL here is the file for running the notebook.
[redshift_catalog.npy.zip](https://github.com/CosmoStat/jax-lensing/files/5638668/redshift_catalog.npy.zip)

**Comment by liuxx479** [comment]
@EiffL correction: do no normalize the lensing kernel, and we get:
![image](https://user-images.githubusercontent.com/2658222/101390830-4b91a800-3878-11eb-90eb-e87351f3aa02.png)
A=1.2 seems to match the COSMOS lensing kernel the best.

Final weights for each kappaTNG zs planes (account for the zs_center and different delta_z for kappaTNG runs, since zs was equally spaced in comoving space with thickness 102.5Mpc/h, not redshift):

![image](https://user-images.githubusercontent.com/2658222/101390954-73810b80-3878-11eb-81ed-7131bb410fe1.png)

zs = array([0.034, 0.07 , 0.105, 0.142, 0.179, 0.216, 0.255, 0.294, 0.335,
       0.376, 0.418, 0.462, 0.506, 0.552, 0.599, 0.648, 0.698, 0.749,
       0.803, 0.858, 0.914, 0.973, 1.034, 1.097, 1.163, 1.231, 1.302,
       1.375, 1.452, 1.532, 1.615, 1.703, 1.794, 1.889, 1.989, 2.094,
       2.203, 2.319, 2.44 , 2.568])

weights = array([0.0025972 , 0.00282821, 0.00547208, 0.00394597, 0.0065455 ,
       0.00995475, 0.00816962, 0.01029778, 0.01376537, 0.01401739,
       0.01235127, 0.01561818, 0.01502547, 0.01662392, 0.02416116,
       0.02685403, 0.030863  , 0.03450561, 0.02412149, 0.03820889,
       0.04268923, 0.03597806, 0.02898686, 0.03332719, 0.0457648 ,
       0.03326885, 0.03681345, 0.02626132, 0.03751817, 0.02449252,
       0.02652501, 0.02184865, 0.02355912, 0.01751766, 0.02866484,
       0.0193798 , 0.01721197, 0.0184604 , 0.01650958, 0.14929563])

**Comment by EiffL** [comment]
I;m gonna mark this as done :-)
